# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, The OpenROAD Authors

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_flex//flex:flex.bzl", "flex_cc_library")
load("@rules_bison//bison:bison.bzl", "bison_cc_library")
load("//bazel:tcl_encode_sta.bzl", "tcl_encode_sta")
load("//bazel:tcl_wrap_cc.bzl", "tcl_wrap_cc")

package(
    default_visibility = ["//:__subpackages__"],
    #    features = ["layering_check"],
)

# Generate location header files for parsers that use custom location file names
# These files would normally be generated by bison, but rules_bison doesn't collect them
genrule(
    name = "location_headers",
    srcs = [
        "verilog/VerilogParse.yy",
        "liberty/LibertyParse.yy",
        "parasitics/SpefParse.yy",
        "sdf/SdfParse.yy",
        "power/SaifParse.yy",
    ],
    outs = [
        "verilog/VerilogLocation.hh",
        "liberty/LibertyLocation.hh",
        "parasitics/SpefLocation.hh",
        "sdf/SdfLocation.hh",
        "power/SaifLocation.hh",
    ],
    cmd = """
        # Use bison to generate location headers
        BISON=$$(which bison || echo "")
        if [ -z "$$BISON" ]; then
            echo "Error: bison not found in PATH" >&2
            exit 1
        fi

        # Save current directory
        ORIG_DIR=$$(pwd)

        # Create a temporary working directory
        WORKDIR=$$(mktemp -d)
        trap "rm -rf $$WORKDIR" EXIT

        # Generate VerilogLocation.hh
        cd $$WORKDIR
        $$BISON --language=c++ --defines=VerilogParse.h -o VerilogParse.cc $$ORIG_DIR/$(location verilog/VerilogParse.yy) 2>/dev/null
        if [ -f VerilogLocation.hh ]; then
            cp VerilogLocation.hh $$ORIG_DIR/$(location verilog/VerilogLocation.hh)
        else
            echo "Warning: Failed to generate VerilogLocation.hh" >&2
            echo '#include "location.hh"' > $$ORIG_DIR/$(location verilog/VerilogLocation.hh)
        fi
        rm -f VerilogParse.* VerilogLocation.hh

        # Generate LibertyLocation.hh
        $$BISON --language=c++ --defines=LibertyParse.h -o LibertyParse.cc $$ORIG_DIR/$(location liberty/LibertyParse.yy) 2>/dev/null
        if [ -f LibertyLocation.hh ]; then
            cp LibertyLocation.hh $$ORIG_DIR/$(location liberty/LibertyLocation.hh)
        else
            echo "Warning: Failed to generate LibertyLocation.hh" >&2
            echo '#include "location.hh"' > $$ORIG_DIR/$(location liberty/LibertyLocation.hh)
        fi
        rm -f LibertyParse.* LibertyLocation.hh

        # Generate SpefLocation.hh
        $$BISON --language=c++ --defines=SpefParse.h -o SpefParse.cc $$ORIG_DIR/$(location parasitics/SpefParse.yy) 2>/dev/null
        if [ -f SpefLocation.hh ]; then
            cp SpefLocation.hh $$ORIG_DIR/$(location parasitics/SpefLocation.hh)
        else
            echo "Warning: Failed to generate SpefLocation.hh" >&2
            echo '#include "location.hh"' > $$ORIG_DIR/$(location parasitics/SpefLocation.hh)
        fi
        rm -f SpefParse.* SpefLocation.hh

        # Generate SdfLocation.hh
        $$BISON --language=c++ --defines=SdfParse.h -o SdfParse.cc $$ORIG_DIR/$(location sdf/SdfParse.yy) 2>/dev/null
        if [ -f SdfLocation.hh ]; then
            cp SdfLocation.hh $$ORIG_DIR/$(location sdf/SdfLocation.hh)
        else
            echo "Warning: Failed to generate SdfLocation.hh" >&2
            echo '#include "location.hh"' > $$ORIG_DIR/$(location sdf/SdfLocation.hh)
        fi
        rm -f SdfParse.* SdfLocation.hh

        # Generate SaifLocation.hh
        $$BISON --language=c++ --defines=SaifParse.h -o SaifParse.cc $$ORIG_DIR/$(location power/SaifParse.yy) 2>/dev/null
        if [ -f SaifLocation.hh ]; then
            cp SaifLocation.hh $$ORIG_DIR/$(location power/SaifLocation.hh)
        else
            echo "Warning: Failed to generate SaifLocation.hh" >&2
            echo '#include "location.hh"' > $$ORIG_DIR/$(location power/SaifLocation.hh)
        fi
        rm -f SaifParse.* SaifLocation.hh
    """,
)

# Wrapper headers to make generated .h files available as .hh
genrule(
    name = "parser_hh_wrappers",
    outs = [
        "verilog/VerilogParse.hh",
        "liberty/LibExprParse.hh",
        "liberty/LibertyParse.hh",
        "parasitics/SpefParse.hh",
        "sdf/SdfParse.hh",
        "power/SaifParse.hh",
    ],
    cmd = """
        echo '#include "VerilogParse.h"' > $(location verilog/VerilogParse.hh)
        echo '#include "LibExprParse.h"' > $(location liberty/LibExprParse.hh)
        echo '#include "LibertyParser.h"' > $(location liberty/LibertyParse.hh)
        echo '#include "SpefParser.h"' > $(location parasitics/SpefParse.hh)
        echo '#include "SdfParser.h"' > $(location sdf/SdfParse.hh)
        echo '#include "SaifParser.h"' > $(location power/SaifParse.hh)
    """,
)

# Header-only library to provide includes for flex/bison generated code
cc_library(
    name = "sta_headers",
    hdrs = glob([
        "dcalc/*.hh",
        "liberty/*.hh",
        "parasitics/*.hh",
        "power/*.hh",
        "sdc/*.hh",
        "sdf/*.hh",
        "search/*.hh",
        "spice/*.hh",
        "util/*.hh",
        # verilog/*.hh excluded due to VerilogScanner.hh including generated files
        "include/sta/*.hh",
    ]) + [
        ":StaConfig",  # Generated config header
        ":parser_hh_wrappers",  # Wrapper headers for .h -> .hh
        ":location_headers",  # Location headers for bison parsers
    ],
    includes = [
        ".",
        "include",
        "include/sta",
        "util",  # For StaConfig.hh
        "verilog",  # For generated VerilogParse.hh
        "liberty",  # For generated LibExprParse.hh and LibertyParse.hh
        "parasitics",  # For generated SpefParse.hh
        "sdf",  # For generated SdfParse.hh
        "power",  # For generated SaifParse.hh
    ],
    deps = [
        "@rules_flex//flex:current_flex_toolchain",  # Provides FlexLexer.h for scanner headers
    ],
)

flex_cc_library(
    name = "LibExprLex",
    src = "liberty/LibExprLex.ll",
    flex_options = ["-P", "LibExprLex_"],
    deps = [
        ":sta_headers",
        ":LibExprParse",  # Needs LibExprParse.hh
    ],
)

bison_cc_library(
    name = "LibExprParse",
    src = "liberty/LibExprParse.yy",
    bison_options = ["-p", "LibExprParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

# Liberty Parser
flex_cc_library(
    name = "LibertyLex",
    src = "liberty/LibertyLex.ll",
    flex_options = ["-P", "LibertyLex_"],
    deps = [
        ":sta_headers",
        ":LibertyParser",  # Needs LibertyParse.hh
    ],
)

bison_cc_library(
    name = "LibertyParser",
    src = "liberty/LibertyParse.yy",
    bison_options = ["-p", "LibertyParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

# Spef scan/parse.
flex_cc_library(
    name = "SpefLex",
    src = "parasitics/SpefLex.ll",
    flex_options = ["-P", "SpefLex_"],
    deps = [
        ":sta_headers",
        ":SpefParser",  # Needs SpefParse.hh
    ],
)

bison_cc_library(
    name = "SpefParser",
    src = "parasitics/SpefParse.yy",
    bison_options = ["-p", "SpefParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

# Verilog scan/parse.
flex_cc_library(
    name = "VerilogLex",
    src = "verilog/VerilogLex.ll",
    flex_options = ["-P", "VerilogLex_"],
    deps = [
        ":sta_headers",
        ":VerilogParse",  # Needs VerilogParse.hh and location.hh
    ],
)

bison_cc_library(
    name = "VerilogParse",
    src = "verilog/VerilogParse.yy",
    bison_options = ["-p", "VerilogParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

# sdf scan/parse.
flex_cc_library(
    name = "SdfLex",
    src = "sdf/SdfLex.ll",
    flex_options = ["-P", "SdfLex_"],
    deps = [
        ":sta_headers",
        ":SdfParser",  # Needs SdfParse.hh
    ],
)

bison_cc_library(
    name = "SdfParser",
    src = "sdf/SdfParse.yy",
    bison_options = ["-p", "SdfParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

flex_cc_library(
    name = "SaifLex",
    src = "power/SaifLex.ll",
    flex_options = ["-P", "SaifLex_"],
    deps = [
        ":sta_headers",
        ":SaifParser",  # Needs SaifParse.hh
    ],
)

bison_cc_library(
    name = "SaifParser",
    src = "power/SaifParse.yy",
    bison_options = ["-p", "SaifParse_", "-S", "lalr1.cc"],
    deps = [":sta_headers"],
)

# The order here is very important as the script to encode these relies on it
tcl_srcs = [
    "tcl/Util.tcl",
    "tcl/CmdUtil.tcl",
    "tcl/Init.tcl",
    "tcl/CmdArgs.tcl",
    "tcl/Property.tcl",
    "tcl/Sta.tcl",
    "tcl/Variables.tcl",
    "tcl/Splash.tcl",
    "graph/Graph.tcl",
    "liberty/Liberty.tcl",
    "network/Link.tcl",
    "network/Network.tcl",
    "network/NetworkEdit.tcl",
    "search/Search.tcl",
    "dcalc/DelayCalc.tcl",
    "parasitics/Parasitics.tcl",
    "power/Power.tcl",
    "sdc/Sdc.tcl",
    "sdf/Sdf.tcl",
    "verilog/Verilog.tcl",
]

exports_files([
    "etc/TclEncode.tcl",
])

exported_tcl = [
    "tcl/Util.tcl",
    "tcl/CmdUtil.tcl",
    "tcl/CmdArgs.tcl",
    "tcl/Property.tcl",
    "tcl/Splash.tcl",
    "tcl/Sta.tcl",
    "tcl/Variables.tcl",
    "sdc/Sdc.tcl",
    "sdf/Sdf.tcl",
    "search/Search.tcl",
    "dcalc/DelayCalc.tcl",
    "graph/Graph.tcl",
    "liberty/Liberty.tcl",
    "network/Network.tcl",
    "network/NetworkEdit.tcl",
    "parasitics/Parasitics.tcl",
    "power/Power.tcl",
]

filegroup(
    name = "tcl_scripts",
    srcs = exported_tcl,
    visibility = [
        "//:__subpackages__",
    ],
)

tcl_encode_sta(
    name = "StaTclInitVar",
    srcs = tcl_srcs,
    char_array_name = "tcl_inits",
)

genrule(
    name = "StaConfig",
    srcs = [],
    outs = ["util/StaConfig.hh"],
    cmd = """echo -e '
    #define STA_VERSION "2.7.0"
    #define STA_GIT_SHA1 "f21d4a3878e2531e3af4930818d9b5968aad9416"
    #define SSTA 0
    #define ZLIB_FOUND' > \"$@\"
    """,
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "sta_swig_files",
    srcs = [
        "app/StaApp.i",
        "dcalc/DelayCalc.i",
        "graph/Graph.i",
        "liberty/Liberty.i",
        "network/Network.i",
        "network/NetworkEdit.i",
        "parasitics/Parasitics.i",
        "power/Power.i",
        "sdc/Sdc.i",
        "sdf/Sdf.i",
        "search/Property.i",
        "search/Search.i",
        "spice/WriteSpice.i",
        "tcl/Exception.i",
        "tcl/StaTclTypes.i",
        "util/Util.i",
        "verilog/Verilog.i",
    ],
    visibility = ["//:__subpackages__"],
)

tcl_wrap_cc(
    name = "StaApp",
    srcs = [
        ":sta_swig_files",
    ],
    namespace_prefix = "sta",
    root_swig_src = "app/StaApp.i",
    swig_includes = [
        ".",
    ],
)

cc_binary(
    name = "opensta",
    srcs = [
        "app/Main.cc",
        ":StaApp",
        ":StaTclInitVar",
        "//bazel:runfiles",
    ],
    copts = [
        "-Wno-error",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-Wno-cast-qual",  # typically from TCL swigging
        "-Wno-missing-braces",  # typically from TCL swigging
        "-Wredundant-decls",
        "-Wformat-security",
        "-Wno-unused-parameter",
        "-Wno-sign-compare",
    ],
    features = ["-use_header_modules"],
    includes = [
        "",
        "dcalc",
        "include/sta",
        "util",
    ],
    malloc = "@tcmalloc//tcmalloc",
    visibility = ["//visibility:public"],
    deps = [
        ":opensta_lib",
        "@rules_cc//cc/runfiles",
        "@tcl",
    ],
)

cc_library(
    name = "opensta_lib",
    srcs = glob(
        include = [
            "dcalc/*.cc",
            "dcalc/*.hh",
            "graph/*.cc",
            "liberty/*.cc",
            "liberty/*.hh",
            "network/*.cc",
            "parasitics/*.cc",
            "parasitics/*.hh",
            "power/*.cc",
            "power/*.hh",
            "sdc/*.cc",
            "sdc/*.hh",
            "sdf/*.cc",
            "sdf/*.hh",
            "search/*.cc",
            "search/*.hh",
            "spice/*.cc",
            "spice/*.hh",
            "tcl/*.cc",
            "util/*.cc",
            "util/*.hh",
            "verilog/*.cc",
            "verilog/*.hh",
        ],
        exclude = [
            "graph/Delay.cc",
            "liberty/LibertyExt.cc",
            "util/Machine*.cc",
        ],
    ) + [
        "app/StaMain.cc",
        "util/Machine.cc",
        ":StaConfig",
    ],
    #+ select({
    #        "@bazel_tools//src/conditions:windows": ["util/MachineWin32.cc"],
    #        "@bazel_tools//src/conditions:darwin": ["util/MachineApple.cc"],
    #        "@bazel_tools//src/conditions:linux": ["util/MachineLinux.cc"],
    #        "//conditions:default": ["util/MachineUnknown.cc"],
    #    })
    hdrs = glob(
        include = ["include/sta/*.hh"],
    ) + [
        # Required for swig
        "search/Tag.hh",
        "dcalc/ArcDcalcWaveforms.hh",
        "power/Power.hh",
        "power/VcdReader.hh",
        "power/SaifReader.hh",
        "sdf/SdfReader.hh",
        "sdf/ReportAnnotation.hh",
        "sdf/SdfWriter.hh",
        "search/Levelize.hh",
        "search/ReportPath.hh",
        "spice/WritePathSpice.hh",
        "dcalc/PrimaDelayCalc.hh",
    ],
    copts = [
        "-Wno-error",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-Wno-cast-qual",  # typically from TCL swigging
        "-Wno-missing-braces",  # typically from TCL swigging
        "-Wredundant-decls",
        "-Wformat-security",
        "-Wno-unused-parameter",
        "-Wno-sign-compare",
        "-fopenmp",
    ],
    features = [
        "-use_header_modules",
    ],
    includes = [
        ".",
        "dcalc",
        "include",
        "include/sta",
        "liberty",
        "parasitics",
        "power",
        "sdf",
        "util",
        "verilog",
    ],
    textual_hdrs = ["util/MachineLinux.cc"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":LibExprLex",
        ":LibExprParse",
        ":LibertyLex",
        ":LibertyParser",
        ":SaifLex",
        ":SaifParser",
        ":SdfLex",
        ":SdfParser",
        ":SpefLex",
        ":SpefParser",
        ":VerilogLex",
        ":VerilogParse",
        "@cudd",
        "@eigen",
        "@openmp",
        "@rules_flex//flex:current_flex_toolchain",
        "@tcl",
        "@zlib",
    ],
)

filegroup(
    name = "tcl_util",
    srcs = [
        "tcl/Util.tcl",
    ],
    visibility = ["//visibility:public"],
)
